# mainatiner: nick.reva@snap.com
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
#test for Yi!
  # set up root access
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  NodeCount = 1

  # configure Kubernetes Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      # set base image for the vagrant box
      config.vm.box = "opensuse/Leap-15.2.x86_64"

      # set the static IP for the vagrant box
      node.vm.network "private_network", ip: "192.168.50.4"
      # configure the parameters for VirtualBox provider
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 4048
        v.cpus = 2
      end

    config.vm.provision "shell", inline: <<-SHELL
      sudo zypper --non-interactive install apparmor-parser
      # install Docker
      zypper --non-interactive install docker #python3-docker-compose
      systemctl enable docker
      usermod -G docker -a $USER
      systemctl restart docker
      # dasable firewall
      # echo "[TASK 2] Disable firewalld"
      # systemctl stop firewalld
      # systemctl disable firewalld
      # # disable apparmor
      # echo "[TASK 3] Disable apparmor"
      # systemctl stop apparmor
      # systemctl disable apparmor
      # # set up rke user
      # echo "[TASK 4] Set up rke user"
      # useradd rke
      # usermod -a -G docker rke
      # systemctl restart docker
      # # copy auth_keys for rke user
      # echo "[TASK 5] Copy auth_keys for rke user"
      # mkdir -p /home/rke/.ssh
      # usermod -d /home/rke/ rke
      # cp /root/.ssh/authorized_keys /home/rke/.ssh
      # chown rke /home/rke -R
    SHELL
    end
    config.vm.synced_folder ".", "/home/"
  end
end
